quarkus.package.jar.type=uber-jar

quarkus.banner.enabled=false
quarkus.log.level=ERROR
quarkus.log.console.enable=true
quarkus.log.console.level=ERROR

quarkus.log.category."io.quarkus".level=OFF
quarkus.log.category."io.quarkus.runtime".level=ERROR
quarkus.log.category."org.jboss".level=OFF

# Native image
quarkus.native.additional-build-args=\
  -Os,\
  --enable-native-access=ALL-UNNAMED,\
  --initialize-at-run-time=org.jline.nativ,\
  --initialize-at-run-time=org.jline.terminal.impl.jansi,\
  --initialize-at-run-time=org.jline.terminal.impl.ffm,\
  --initialize-at-run-time=jdk.internal.org.jline.terminal.impl.ffm,\
  --initialize-at-run-time=com.github.dockerjava.transport.NamedPipeSocket$Kernel32,\
  --initialize-at-run-time=org.newsclub.net.unix,\
  --initialize-at-run-time=com.fasterxml.jackson.module.jaxb.deser.DataHandlerJsonDeserializer

# Fixes "Cannot load required properties from maven-build.properties" error
# when run streamx-runner with native-image executable.
quarkus.native.resources.includes=maven-build.properties