#Properties
argLine=
assertj-core.version=3.24.2
checkstyle-plugin.version=3.2.0
cloudevents.version=4.0.1
compiler-plugin.version=3.13.0
docker-java.version=3.7.0
envoy.container.version=v1.6.1
failsafe-plugin.version=3.1.2
gizmo.version=1.7.0
google-re2j.version=1.7
jacoco-plugin.version=0.8.11
jandex-maven-plugin.version=3.2.0
javax.ws.rs-api.version=2.1.1
jaxb-api.version=2.3.1
junit-platform-suite.version=1.10.0
maven-jar-plugin.version=3.3.0
maven.compiler.release=21
maven.compiler.source=21
maven.compiler.target=21
otel-lgtm.container.version=0.9.1
project.build.sourceEncoding=UTF-8
project.reporting.outputEncoding=UTF-8
properties-maven-plugin.version=1.2.1
pulsar-client.version=4.1.3
pulsar.version=4.1.3
quarkus-reactive-messaging-http.version=2.7.0
quarkus-wiremock-test.version=1.5.0
quarkus.container-image.additional-tags=latest-jvm
quarkus.container-image.build=true
quarkus.container-image.gcp.project.id=streamx-releases
quarkus.container-image.group=streamx-releases/streamx-docker-snapshots/streamx-service-mesh
quarkus.container-image.location=europe-west1
quarkus.container-image.name=streamx-runner
quarkus.container-image.package.type=jvm
quarkus.container-image.registry=europe-west1-docker.pkg.dev
quarkus.container-image.repository.name=streamx-docker-snapshots
quarkus.container-image.tag=2.0.23-SNAPSHOT-jvm
quarkus.package.main-class=com.streamx.runner.main.Main
quarkus.platform.artifact-id=quarkus-bom
quarkus.platform.group-id=io.quarkus.platform
quarkus.platform.version=3.20.4
streamx.container-image.latest-tag=latest-jvm
streamx.container-image.package.type.jvm=jvm
streamx.container-image.package.type.native=native
streamx.services-supporting-native-build.tag=2.0.23-SNAPSHOT-jvm
surefire-plugin.version=3.1.2
tomcat-annotations-api.version=9.0.80
wiremock.version=3.13.1
