quarkus.banner.enabled=false
quarkus.log.level=ERROR
quarkus.log.console.enable=true
quarkus.log.console.level=ERROR

quarkus.log.category."io.quarkus".level=OFF
quarkus.log.category."org.jboss".level=OFF

quarkus.native.additional-build-args=--enable-native-access=ALL-UNNAMED,--initialize-at-run-time=org.jline,--initialize-at-run-time=org.mozilla.universalchardet,--initialize-at-run-time=com.fasterxml.jackson.module.jaxb.deser.DataHandlerJsonDeserializer,--initialize-at-run-time=com.streamx.cli.i18n.MessageProvider,--initialize-at-run-time=org.testcontainers,--initialize-at-run-time=com.github.dockerjava,--features=com.streamx.cli.nativeimage.DockerJavaFeature