quarkus.banner.enabled=false
quarkus.log.level=ERROR
quarkus.log.console.enable=true
quarkus.log.console.level=ERROR

quarkus.log.category."io.quarkus".level=OFF
quarkus.log.category."org.jboss".level=OFF